# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew.
#
# The context of this file is that of a software developer trying to publish their
# software on Homebrew (https://brew.sh).
class DuoChat < Formula
  desc "Unofficial Duo Chat for macOS"
  homepage "https://gitlab.com/tachyons-gitlab/duo-chat-macos"
  version "0.1.0"
  sha256 "176640490ca993b9e73802f6de8864fc65a6dcffcdce38367d88f6d427a1ef9e"

  url "https://gitlab.com/tachyons-gitlab/duo-chat-macos/-/archive/v0.1.0/duo-chat-macos-v0.1.0.tar.gz"
  license "MIT"

  depends_on "make" => :build
  depends_on :xcode => "14.0"

  def install
    system "make", "build-release"
    prefix.install "build/duo-chat.app"
  end

  test do
    # `test do` will create, run in and delete a temporary directory.
    #
    # This test will fail and we won't accept that! For Homebrew/homebrew-core
    # this will need to be a test that verifies the functionality of the
    # software. Run the test with `brew test duo-chat`. Options passed
    # to `brew install` such as `--HEAD` also need to be provided to `brew test`.
    #
    # The installed folder is not in the path, so use the entire path to any
    # executables being tested: `system "#{bin}/program", "do", "something"`.
    assert_predicate prefix/"duo-chat.app", :exist?
  end
end
