name: Build Duo Chat

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: "duo-chat"
  SCHEME_NAME: "duo-chat"

jobs:
  build-and-release:
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        fi
    
    - name: Build and package app
      run: make build-release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
      with:
        name: duo-chat-${{ steps.version.outputs.version }}
        path: |
          ${{ env.APP_NAME }}.zip
          ${{ env.APP_NAME }}.dmg
          checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: "Duo Chat ${{ steps.version.outputs.version }}"
        body: |
          ## 🚀 Duo Chat ${{ steps.version.outputs.version }}
          
          GitLab AI Chat Client for macOS
          
          ### Installation
          ⚠️ This is an unsigned app. Right-click and select "Open" on first launch.
          
          Built from: `${{ github.sha }}`
        files: |
          ${{ env.APP_NAME }}.zip
          ${{ env.APP_NAME }}.dmg
          checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-app:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build and test
      run: |
        make build
        make test
